# --------------------------
# English language
# --------------------------
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# --------------------------
# french language
# --------------------------
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

# --------------------------
# Spanish language
# --------------------------
[es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 3
